#!/usr/bin/env python
# -*- coding: utf-8 -*-

import time
import rospy
import std_msgs
import axis
import json
import os
import json


from arom_helper import AromNode


class TelescopePatrolaCtrl(AromNode):
    node_name = "patrola_ctrl"
    node_type = "patrola_ctrl"
    node_pymlab = True

    def __init__(self):
        print os.path.dirname(os.path.realpath(__file__))
        print os.getcwd()
        print __file__
        print __file__+'.feature.hbs'


        AromNode.__init__(self)
        node_name = rospy.get_name()
        self.node_name = node_name
        print node_name

        print "config file:", '/home/odroid/config'+node_name+'.json'
        with open('/home/odroid/config'+node_name+'.json') as json_data:
            self.conf = json.load(json_data)

        print self.conf


        self.pub_motor_a = rospy.Publisher(node_name+"/motor_focus", std_msgs.msg.String, queue_size=1)
        self.pub_motor_b = rospy.Publisher(node_name+"/motor_clona", std_msgs.msg.String, queue_size=1)
        self.pub_ostreni_pos = rospy.Publisher(node_name+"/ostreni/position", std_msgs.msg.String, queue_size=1, latch = True)
        self.pub_iris_pos = rospy.Publisher(node_name+"/iris/position", std_msgs.msg.String, queue_size=1, latch = True)

        self.sub_iris_request = rospy.Subscriber("/ui/keyboard/out", std_msgs.msg.String, self.ui_action)
        self.sub_ostreni_request = rospy.Subscriber(node_name+"/ostreni/command", std_msgs.msg.String, self.ostreni_set)
        self.ostreni_request = 10
        self.ostreni_zmena = True
        self.sub_iris_request = rospy.Subscriber(node_name+"/iris/command", std_msgs.msg.String, self.iris_set)
        self.iris_request = 10
        self.iris_zmena = True
        self.operation = []

        
        self.set_feature('external',  {'feature': __file__+'.feature.hbs', 'id': 'motor_focus', 'name': 'Motor Ostreni', 'node_name': node_name, 'toppic': node_name+'/motor_focus', 'iris_range': self.conf['iris']['range'], 'focus_range': self.conf['focus']['range']})
        self.set_feature('hbstep_status__0',  {'id': 'motor_focus', 'name': 'Motor Ostreni', 'node_name': node_name, 'toppic': node_name+'/motor_focus'})
        self.set_feature('hbstep_status__1',  {'id': 'motor_clona', 'name': 'Motor Clona', 'node_name': node_name, 'toppic': node_name+'/motor_clona'})
        
        print "AXIS::::", node_name[1:]
        self.motor_a = axis.axis(SPI = self.pymlab, SPI_CS = 0b0001, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = node_name[1:])
        self.motor_a.Setup(MAX_SPEED = 700,
                       KVAL_ACC=0.4,
                       KVAL_RUN=0.35,
                       KVAL_DEC=0.4,
                       ACC = 20,
                       DEC = 100,
                       FS_SPD=3000,
                       STEP_MODE=None)
        self.motor_a.Float()
        self.motor_a.MaxSpeed(100)
        self.motor_a.SetSwRange(self.conf['focus']['min'], self.conf['focus']['max'])


        self.motor_b = axis.axis(SPI = self.pymlab, SPI_CS = 0b0010, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = node_name[1:])  
        self.motor_b.Setup(MAX_SPEED = 700,
                       KVAL_ACC=0.4,
                       KVAL_RUN=0.35,
                       KVAL_DEC=0.4,
                       ACC = 20,
                       DEC = 100,
                       FS_SPD=3000,
                       STEP_MODE=None)
        self.motor_b.Float()
        self.motor_b.MaxSpeed(0x33FF)
        self.motor_b.SetSwRange(self.conf['iris']['min'], self.conf['iris']['max'])


        self.motor_a.GoTo(self.conf['focus']['min']-self.conf['focus']['max'])
        self.motor_b.GoTo(self.conf['iris']['min']-self.conf['iris']['max'])

        while self.motor_a.IsBusy() or self.motor_b.IsBusy():
            time.sleep(0.4)

        print "prejezd do vychozi polohy"
        self.motor_a.GoTo(self.conf['focus']['home'])
        self.motor_b.GoTo(self.conf['iris']['home'])
        while self.motor_a.IsBusy() or self.motor_b.IsBusy():
            time.sleep(0.4)
        print "jsem uprostred"

        self.motor_a.Float()
        self.motor_b.Float()

        i = 0
        nn = self.node_name[1:]
        rate = rospy.Rate(5)
        while not rospy.is_shutdown():
            rate.sleep()
            try:

                i += 1
                if i > 10:
                    i = 0
                    self.motor_a_status = self.motor_a.getStatus()
                    self.motor_b_status = self.motor_b.getStatus()
                    #print self.motor_a_status
                    self.pub_motor_a.publish(json.dumps(self.motor_a_status, ensure_ascii=False))
                    self.pub_motor_b.publish(json.dumps(self.motor_b_status, ensure_ascii=False))
                    self.pub_ostreni_pos.publish(str(self.motor_a_status['POSITION_SW']))
                    self.pub_iris_pos.publish(str(self.motor_b_status['POSITION_SW']))
                #if (self.motor_a_status['POSITION'] != self.ostreni_request):
                if (self.ostreni_zmena):
                    rospy.loginfo("Motor FOCUS reapir position %s na %s" %(self.motor_a_status['POSITION_CLC'],  self.ostreni_request))
                    self.motor_a.GoTo(self.ostreni_request)
                    self.ostreni_zmena = False
                    #self.pub_ostreni_pos.publish(str(self.ostreni_request))
                    self.pub_ostreni_pos.publish(str(self.motor_a_status['POSITION_SW']))

                #if (self.motor_b_status['POSITION'] != self.iris_request):
                if (self.iris_zmena):
                    rospy.loginfo("Motor IRIS reapir position %s na %s" %(self.motor_b_status['POSITION_CLC'],  self.iris_request))
                    self.motor_b.GoTo(self.iris_request)
                    self.iris_zmena = False
                    #self.pub_iris_pos.publish(str(self.iris_request))
                    self.pub_iris_pos.publish(str(self.motor_b_status['POSITION_SW']))


                if len(self.operation)>0:
                    req = self.operation.pop(0)
                    print req

                    if req == nn+'_focusM1':
                        self.motor_a.GoTo(self.conf['focus']['min'])

                    elif req == nn+'_focusP1':
                        self.motor_a.GoTo(self.conf['focus']['max'])

                    elif req == nn+'_focusM0' or req == nn+'_focusP0':
                        self.motor_a.Float()


                    elif req == nn+'_irisM1':
                        self.motor_b.GoTo(self.conf['iris']['min'])

                    elif req == nn+'_irisP1':
                        self.motor_b.GoTo(self.conf['iris']['max'])

                    elif req == nn+'_irisM0' or req == nn+'_irisP0':
                        self.motor_b.Float()
                
            except Exception, e:
                print "err1>", repr(e)


        self.motor_a.Float()
        self.motor_b.Float()

    def ostreni_set(self, data):
        print "ostreni", data
        rospy.loginfo(data.data)
        poloha =float(data.data)

        if poloha > 100: poloha = 100
        elif poloha < 0: poloha = 0

        poloha = int(float(poloha)*(self.conf['focus']['max']-self.conf['focus']['min'])/100+self.conf['focus']['min'])
        print "^^ ", poloha

        self.ostreni_request = int(poloha)
        self.ostreni_zmena = True

    def iris_set(self, data):
        print "iris", data
        rospy.loginfo(data.data)
        poloha = float(data.data)

        if poloha > 100: poloha = 100
        elif poloha < 0: poloha = 0

        #poloha =    int(float(poloha)*(self.conf['focus']['max']-self.conf['focus']['min'])/100+self.conf['focus']['min'])
        poloha = int(float(poloha)*(self.conf['iris']['max']-self.conf['iris']['min'])/100+self.conf['iris']['min'])
        print "^^ ", poloha

        self.iris_request = int(poloha)
        self.iris_zmena = True

    def motor_calibrate():
        pass

    def ui_action(self, msg):
        data = msg.data
        nn = self.node_name[1:]
        if data in [nn+'_close1', nn+'_irisM0', nn+'_irisM1', nn+'_irisP0', nn+'_irisP1', nn+'_focusM0', nn+'_focusM1', nn+'_focusP0', nn+'_focusP1']:
            print "zprava prijata", data
            self.operation.append(data)
            #if data == nn+'_close1':
            #    self.motor_clona.GoTo(10)



if __name__ == '__main__':
    time.sleep(6)
    m = TelescopePatrolaCtrl()
